object Versions {
    const val agp = "8.7.1"
    const val kotlin = "2.1.0"
    const val coreKtx = "1.13.1"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val espressoCore = "3.6.1"
    const val lifecycleRuntimeKtx = "2.8.7"
    const val activityCompose = "1.9.3"
    const val composeBom = "2024.04.01"
    const val mvikotlinVersion = "4.2.0"
    const val decomposeVersion = "3.2.2"
    const val roomVersion = "2.6.1"
    const val kspVersion = "2.1.0-1.0.29"
    const val daggerVersion = "2.54"
    const val glideVersion = "1.0.0-beta01"
    const val retrofitVersion = "2.9.0"
    const val jetbrainsKotlinJvm = "2.1.0"
    const val appcompat = "1.7.0"
    const val material = "1.12.0"
    const val gradleToolsVersion = "8.7.3"
}